site_name: Documentation Guides

docs_dir: Docs

pages:
- ['index.md','Introduction to the Documentation Guides']
- ['publishing_guide.md', 'Guides', 'Publishing guide']
- ['style_guide.md', 'Guides', 'Style guide']
- ['writing_guide.md', 'Guides', 'Writing guide']
- ['product_names.md', 'Guides', 'Product names']
