site_name: Documentation Guides

docs_dir: Docs

pages:
- Introduction to the Documentation Guides: 'index.md'
- Guides:
  - 'Publishing guide': 'publishing_guide.md'
  - 'Style guide': 'style_guide.md'
  - 'Writing guide': 'writing_guide.md'
- Naming:
  - 'Product names': 'product_names.md'
