site_name: Documentation Guides

docs_dir: Docs

pages:
- ['index.md','Introduction to the Documentation Guides']
- ['writing_guide.md', 'Writing Guide', 'Introduction']
- ['writing_tips.md', 'Writing Guide', 'Writing tips']
- ['persona.md', 'Writing Guide', 'Who are your readers?']
- ['maps.md', 'Writing Guide', 'Creating a map before you write']
- ['fleshing_out.md', 'Writing Guide', 'Fleshing out your map']
- ['instructions.md', 'Writing Guide', 'Giving instructions']
- ['Editing.md', 'Writing Guide', 'Editing yourself']
- ['blocks.md', 'Writing Guide', 'Getting over a block']
- ['style_guide.md', 'Style Guide', 'Introduction']
- ['tone.md', 'Style Guide', 'Establishing the right tone']
- ['words.md', 'Style Guide', 'Words, voices and grammar']
- ['punc_cap.md', 'Style Guide', 'Punctuation and capitalization']
- ['product_names.md', 'Style Guide', 'Product names']
- ['examples.md', 'Style Guide', 'Sample edits']
- ['units.md', 'Style Guide', 'Units of measurement']
- ['ambiguity.md', 'Style Guide', 'Ambiguity']
- ['examples.md', 'Style Guide', 'Sample edits']
- ['publishing_guide.md', 'Publising on docs.mbed', 'Publishing guide']
- ['project.md', 'Publising on docs.mbed', 'Creating your own project']


copyright: © ARM Ltd. Copyright 2016 – ARM mbed IoT Device Platform
